### ISSUE TITLE
Incorrect encoding of base64

### ISSUE THREAD

**Issue by ftruter** [0xTim/Vapor-PasskeyDemo#3]
[WebAuthN spec refers to `base64url` encoding, **not** `base64`](https://w3c.github.io/webauthn/#dictionary-client-data)

AFAIK Vapor does not have methods to en/decode base64url yet, [but vapor/core does](Please see https://github.com/vapor/core/blob/main/Sources/Core/Data%2BBase64URL.swift)

What would it take to get support for base64url into Vapor/Vapor or into this project?

**Comment by ftruter** [comment]
Without the proper en/decoding of client tokens this project generates `500 internal server` errors now in all browsers that support WebAuthN

**Comment by 0xTim** [comment]
Yeah there's likely places I've misread the spec, I've noticed a few scenarios where it doesn't work and I get a 500 error. 

In terms of where base64 URL encoding/decoding should live that will be in this package since the end result will be a library that's framework agnostic, so happy to accept a PR. (May or may not be related to #1)

**Comment by 0xTim** [comment]
Closed via #1
